version: "2"
services:
  config:
    image: mongo
    command: mongod --configsvr --dbpath /tmp --port 27019
    ports:
      - "27019:27019"
    volumes:
      - ./db/:/opt/db/

  shard1:
    image: mongo
    command: mongod --dbpath /tmp --port 27018
    ports:
      - "27018:27018"

  shard2:
    image: mongo
    command: mongod --dbpath /tmp --port 27020
    ports:
      - "27020:27020"

  router:
    image: travisjeffery/mongos:1.2.0
    command: mongos --configdb config:27019
    links:
      - config
      - shard1
      - shard2
    depends_on:
      - config
    ports:
      - "27017:27017"