version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  # api:
  #   build: .
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     mongo__host: mongo
  #   links:
  #     - mongo